# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [129]:

import torch
Tensor_A=torch.rand(size=(7,7))
Tensor_A





tensor([[0.9617, 0.7947, 0.9854, 0.4486, 0.9348, 0.1209, 0.1933],
        [0.3675, 0.4221, 0.2888, 0.8662, 0.8032, 0.8405, 0.1754],
        [0.1809, 0.0181, 0.4900, 0.7634, 0.0553, 0.2919, 0.7330],
        [0.6340, 0.7475, 0.8218, 0.5469, 0.5270, 0.6056, 0.5116],
        [0.3307, 0.0465, 0.8827, 0.4925, 0.6722, 0.9138, 0.7463],
        [0.2466, 0.8112, 0.4376, 0.9788, 0.0132, 0.1286, 0.4356],
        [0.5465, 0.4020, 0.7126, 0.8429, 0.0780, 0.9490, 0.8752]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [300]:

Tensor_B=torch.rand(size=(1,7))
Tensor_B=Tensor_B.T
mul=torch.mm(Tensor_A, Tensor_B)
mul




tensor([[3.0205],
        [2.3582],
        [1.3991],
        [2.6490],
        [2.0834],
        [2.1153],
        [2.3088]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [329]:
torch.manual_seed(0)

X=torch.rand(size=(7,7))
Y=torch.rand(size=(1,7))
Y=Y.T
X_Y=torch.mm(X, Y)
X_Y,X_Y.shape



(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [336]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [347]:
# Set random seed
torch.manual_seed(1234)
if(torch.cuda.is_available()):
    device="cuda"
else:
    device="cpu"
print(f"Device: {device} ")


Tensor_1=torch.rand(size=(2,3)).to("cuda")
Tensor_2=torch.rand(size=(2,3)).to("cuda")
Tensor_1,Tensor_2

# Check for access to GPU

# Create two random tensors on GPU


Device: cuda 


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [364]:
matmul=torch.mm(Tensor_1,Tensor_2.T)
matmul,matmul.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [374]:
max=torch.max(matmul)

min=torch.min(matmul)
max,min

# Find min


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [377]:
# Find arg max
arg_max=torch.argmax(matmul)
arg_min=torch.argmin(matmul)
arg_max,arg_min



(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [382]:
torch.manual_seed(7)
rand_tensor=torch.rand(size=(1,1,1,10))
print(rand_tensor,rand_tensor.shape)
rand_tensor2=rand_tensor.squeeze()
print(rand_tensor2,rand_tensor2.shape)



tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
